Added Approcimator
Michael-Tarak/LigaIntensive pull request #1
Opened 2023-10-17 17:21 UTC by Michael-Tarak

Задача выдает ошибку. Причина ошибки - чтение файла сканером как пустого

2023-10-19 20:05 UTC, millerM907 requested changes

2023-10-19 20:05 UTC, millerM907 commented on currencyApprocimator/src/main/java/org/example/CurrencyAnalyzer.java
> +            System.out.println(e.getMessage());
Выводить userfriendly сообщение об ошибке.

2023-10-19 20:05 UTC, millerM907 commented on currencyApprocimator/src/main/java/org/example/services/RateService.java
> +                List<ReportRecordEntity> analysisForDay = report.subList(0,7);
`subList(0,7)` - 0, 7 магические числа.

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/services/CommandReaderService.java
> +    private final int ARGUMENTS_FOR_RATE_COMMAND = 3;
Добавить в наименование слово, указывающее на то, что это именно количество

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/services/CommandReaderService.java
> +                }
Вынести бизнес логику из конструктора. Конструктор должен инициализировать. Логика должна быть прописана в в отдельном методе класса. Соответственно странно, когда вызывается только конструктор, но не вызвано никакого метода.

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/entities/ReportEntity.java
> +import java.util.Scanner;
Убрать лишние импорты (сочетание клавиш Ctrl + Alt + I)

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/entities/ReportEntity.java
> +public class ReportEntity {
В классах из папки entities убрать суффикс Entity из наименования (в 1-ой итерации был про это комментарий). Менять Refactor-ом (Shift + F6 или пункт в меню ПКМ) наименование класса, тогда должно поменяться везде, чтобы вручную не менять.

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/entities/ReportEntity.java
> +        String columnSplitter = ";";
Создать разделитель константой класса (private static final)

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/services/CurrencyAnalyzerService.java
> +            }
Вынести валидацию в отдельный метод, можно в CommandReaderService, например. Сейчас в метод прогнозирования включена валидация команды.

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/services/CurrencyAnalyzerService.java
> +    public void findFutureRateOfCurrency(String currencyType, String ratePeriod) {
Больше подойдет calculate или predict вместо find в наименовании метода

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/reports/euro.csv
Нужно переместить файлы из этой папки в папку src/main/resources

2023-10-22 20:39 UTC, annakoles commented on currencyApprocimator/src/main/java/utils/ReportDateConverter.java
> +    public static LocalDate  ConvertFromCsvStyleToLocalDate(String date) {
Поменять формат наименования метода на camelCase

2023-10-23 20:15 UTC, annakoles commented on currencyApprocimator/src/main/java/entities/ReportRecordEntity.java
> +public class ReportRecordEntity {
Здесь тоже убрать суффикс Entity. Желательно убрать суффикс и в наименованиях объектов класса, тоже Refactor-ом

2023-10-23 20:15 UTC, annakoles commented on currencyApprocimator/src/main/java/utils/ReportDateConverter.java
> +        return LocalDate.parse(dateForConversion, fmt);
Здесь можно не преобразовывать строку date, а поменять символ "-" на "." в паттерне в форматтере

2023-10-23 20:15 UTC, annakoles commented on currencyApprocimator/src/main/java/services/CurrencyAnalyzerService.java
> +    public void predictFutureRateOfCurrency(String currencyType, String ratePeriod) {
Везде в коде перед методом/конструктором добавить одну пустую строку, так код читабельнее.
Убрать двойные пустые строки

2023-10-24 19:17 UTC, millerM907 requested changes

2023-10-24 19:17 UTC, millerM907 commented on currencyApprocimator/src/main/java/services/CommandReaderService.java
> +    private final int ARGUMENTS_FOR_RATE_COMMAND_COUNT = 3;
Переименовать. Имя константы плохо отражает ее суть и может ввести коллегу в заблуждение. Она хранит корректное количество значений массива, представляющих собой команду и 2 ее аргумента. Можно было бы ее назвать `validNumberOfProgramArgs`.

2023-10-25 12:47 UTC, merged